name: Package Updater CI

on:
  push:
    branches:
      - main

jobs:
  run-updater:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Make scripts executable
        run: chmod +x updater.sh run.sh

      - name: Run updater script
        run: sudo ./updater.sh

      - name: Show log file
        run: cat update.log
